name: flutter-rest-client
description: A Dart implementation of the a REST client that supports using an Isolate for decoding.
version: 2.0.1+3
homepage: https://github.com/5ohail/flutter-rest-client

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  intl: ^0.17.0
  json_class: ^2.0.0+1
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.1

dev_dependencies:
  test: ^1.17.12
